# Examining the Data
Both the fulton digest and sales data were already compiled, so we don't actually need to do any of the compiling work here.

**Tax Digest**: fulton_digest_withnonprofit.csv  
**Sales Data**: FULTON_SALES_FINAL.csv

In [1]:
import os
import pandas as pd

In [2]:
SALES_PATH = "/Users/tpeng/Library/CloudStorage/OneDrive-GeorgiaInstituteofTechnology/Housing and Urban Policy (HUP) Lab - Documents/Data Files/Raw Data/ATLSales/FINAL/FULTON_SALES_FINAL.csv"
DIGEST_PATH = "/Users/tpeng/Library/CloudStorage/OneDrive-GeorgiaInstituteofTechnology/Housing and Urban Policy (HUP) Lab - Documents/Data Files/Final Datasets/Fulton/fulton_digest_withnonprofit.csv"

if os.path.exists(SALES_PATH):
    print(f"Sales file present at {SALES_PATH}")
else:
    print(f"Sales file NOT PRESENT, {SALES_PATH} not found.")

if os.path.exists(DIGEST_PATH):
    print(f"Digest file present at {DIGEST_PATH}")
else:
    print(f"Digest file NOT PRESENT, {DIGEST_PATH} not found.")

Sales file present at /Users/tpeng/Library/CloudStorage/OneDrive-GeorgiaInstituteofTechnology/Housing and Urban Policy (HUP) Lab - Documents/Data Files/Raw Data/ATLSales/FINAL/FULTON_SALES_FINAL.csv
Digest file present at /Users/tpeng/Library/CloudStorage/OneDrive-GeorgiaInstituteofTechnology/Housing and Urban Policy (HUP) Lab - Documents/Data Files/Final Datasets/Fulton/fulton_digest_withnonprofit.csv

In [3]:
digest_df = pd.read_csv(DIGEST_PATH, low_memory=False)

In [4]:
digest_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4512096 entries, 0 to 4512095
Data columns (total 61 columns):
 #   Column          Dtype
---  ------          -----
 0   taxyr           int64
 1   parid           object
 2   nbhd            object
 3   situs_adrno     float64
 4   situs_adrdir    float64
 5   situs_adrstr    object
 6   situs_adrsuf    object
 7   situs_adrsuf2   object
 8   situs_cityname  object
 9   class           object
 10  luc             object
 11  livunit         float64
 12  calcacres       float64
 13  ofcard          float64
 14  chgrsn          object
 15  taxdist         object
 16  own1            object
 17  own2            object
 18  owner_adrno     float64
 19  owner_adrdir    object
 20  owner_adrstr    object
 21  owner_adrsuf    object
 22  owner_adrsuf2   object
 23  owner_cityname  object
 24  statecode       object
 25  country         float64
 26  unitno          object
 27  zip1            float64
 28  reascd          object
 29  spcflg          object
 30  aprland         float64
 31  aprbldg         float64
 32  revcode         float64
 33  revreas         object
 34  revland         float64
 35  revbldg         float64
 36  revtot          float64
 37  aprtot          float64
 38  card            float64
 39  stories         float64
 40  extwall         float64
 41  yrblt           float64
 42  effyr           float64
 43  sf              float64
 44  grade           object
 45  cdu             object
 46  pctcomp         float64
 47  cur             object
 48  note1           object
 49  note2           object
 50  mod_own_adrstr  object
 51  mod_unitno      object
 52  owner_addr      object
 53  mod_own_adrno   float64
 54  own_corp_flag   bool
 55  rental_flag     bool
 56  mod_parid       object
 57  ParcelID        object
 58  longitude       float64
 59  latitude        float64
 60  owner_type      object
dtypes: bool(2), float64(25), int64(1), object(33)
memory usage: 2.0+ GB

In [9]:
digest_df.describe()

,taxyr,situs_adrno,situs_adrdir,livunit,calcacres,ofcard,owner_adrno,country,zip1,aprland,...,card,stories,extwall,yrblt,effyr,sf,pctcomp,mod_own_adrno,longitude,latitude
count,4.512096e+06,4.511468e+06,0.0,4.445405e+06,4.495693e+06,4.509166e+06,4.337070e+06,0.0,4.508115e+06,4.511336e+06,...,3.961187e+06,3.961072e+06,3.959047e+06,3.961184e+06,683926.000000,3.961072e+06,8110.000000,4.337070e+06,4.458951e+06,4.458951e+06
mean,2.016103e+03,2.527753e+03,NaN,1.423730e+00,8.491788e-01,1.030966e+00,3.220363e+03,NaN,3.142503e+04,1.291008e+05,...,1.013159e+00,1.433593e+00,4.274933e+00,1.978901e+03,1983.714234,3.142980e+03,35.966954,3.220363e+03,-8.440436e+01,3.382357e+01
std,3.735939e+00,3.158533e+03,NaN,1.235966e+01,1.093615e+01,1.673935e+00,1.783376e+05,NaN,8.808124e+03,1.276919e+06,...,2.648670e-01,6.205470e-01,3.023183e+00,2.658965e+01,15.879560,1.680608e+04,34.564919,1.783376e+05,1.072592e-01,1.681024e-01
min,2.010000e+03,0.000000e+00,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,-3.039000e+03,0.000000e+00,...,1.000000e+00,0.000000e+00,0.000000e+00,1.800000e+03,1891.000000,0.000000e+00,0.000000,0.000000e+00,-8.484486e+01,3.350308e+01
25%,2.013000e+03,3.660000e+02,NaN,1.000000e+00,1.000000e-01,1.000000e+00,4.900000e+02,NaN,3.007600e+04,1.670000e+04,...,1.000000e+00,1.000000e+00,1.000000e+00,1.960000e+03,1970.000000,1.271000e+03,1.000000,4.900000e+02,-8.446878e+01,3.369835e+01
50%,2.016000e+03,1.160000e+03,NaN,1.000000e+00,2.453000e-01,1.000000e+00,1.489000e+03,NaN,3.030900e+04,4.019000e+04,...,1.000000e+00,1.000000e+00,4.000000e+00,1.986000e+03,1985.000000,1.819000e+03,35.000000,1.489000e+03,-8.438996e+01,3.378384e+01
75%,2.019000e+03,3.475000e+03,NaN,1.000000e+00,4.863000e-01,1.000000e+00,3.858000e+03,NaN,3.033100e+04,9.280000e+04,...,1.000000e+00,2.000000e+00,7.000000e+00,2.002000e+03,1995.000000,2.852000e+03,65.000000,3.858000e+03,-8.435371e+01,3.399924e+01
max,2.022000e+03,1.650000e+05,NaN,3.256000e+03,2.000000e+04,1.981000e+03,1.459145e+08,NaN,9.999900e+04,1.261313e+09,...,7.100000e+01,5.600000e+01,1.700000e+01,2.200000e+03,2076.000000,5.148000e+06,100.000000,1.459145e+08,-8.410329e+01,3.418616e+01

In [5]:
sales_df = pd.read_csv(SALES_PATH, low_memory=False)

In [6]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 427617 entries, 0 to 427616
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   tax_year     427617 non-null  int64
 1   parcel_id    427617 non-null  object
 2   luc          427617 non-null  object
 3   saledt       427617 non-null  object
 4   sales_price  427617 non-null  float64
 5   fmv          427617 non-null  float64
 6   deed_type    427612 non-null  object
 7   cost_val     427617 non-null  object
 8   sale_val     427459 non-null  object
 9   grantor      427595 non-null  object
 10  grantee      427610 non-null  object
 11  M_flag       427617 non-null  bool
 12  sale_size    427617 non-null  int64
dtypes: bool(1), float64(2), int64(2), object(8)
memory usage: 39.6+ MB

In [10]:
sales_df.describe()

            tax_year   sales_price           fmv      sale_size
count  427617.000000  4.276170e+05  4.276170e+05  427617.000000
mean     2017.018446  3.552890e+05  4.195910e+05       4.931373
std         3.693748  2.952611e+06  2.690440e+06      19.047611
min      2011.000000  0.000000e+00  0.000000e+00       1.000000
25%      2013.000000  5.127000e+03  8.360000e+04       1.000000
50%      2018.000000  1.385650e+05  1.959000e+05       1.000000
75%      2020.000000  3.280000e+05  3.802000e+05       1.000000
max      2022.000000  6.880000e+08  2.939893e+08     234.000000

In [11]:
OUT_PATH = "../../data/fulton/out"

In [8]:
sales_tax_merged = pd.merge(left=sales_df, right=digest_df, how="left", left_on=["parcel_id", "tax_year"], right_on=["parid", "taxyr"],
                            suffixes=("_sales", ""))

In [12]:
total_rows = sales_tax_merged.shape[0]
merged_rows = sales_tax_merged["parid"].notna().sum()

print(f"{merged_rows / total_rows} succesfully merged.\n {merged_rows} out of {total_rows}")

0.9943266988917653 succesfully merged.
 425191 out of 427617

In [13]:
sales_tax_merged.to_csv(os.path.join(OUT_PATH, "FULTON_SALES_TAX_DIGEST_FINAL.csv"), index=False)

# Investigating Unmerged Rows

In [14]:
unmerged_df = sales_tax_merged[sales_tax_merged["parid"].isna()]
merged_df = sales_tax_merged[sales_tax_merged["parid"].notna()]

Check if any of the numeric columns have odd properties when comparing between merged and unmerged rows.

In [17]:
unmerged_df.describe()

,tax_year,sales_price,fmv,sale_size,taxyr,situs_adrno,situs_adrdir,livunit,calcacres,ofcard,...,card,stories,extwall,yrblt,effyr,sf,pctcomp,mod_own_adrno,longitude,latitude
count,2426.000000,2.426000e+03,2.426000e+03,2426.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2015.354493,2.233559e+05,2.615915e+05,4.676422,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.894512,3.416196e+06,3.318476e+06,14.458572,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2011.000000,0.000000e+00,0.000000e+00,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2013.000000,1.512500e+04,3.312500e+04,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2016.000000,5.100000e+04,5.690000e+04,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2016.000000,1.205128e+05,1.408750e+05,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2022.000000,1.505000e+08,1.386417e+08,214.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
merged_df.describe()

,tax_year,sales_price,fmv,sale_size,taxyr,situs_adrno,situs_adrdir,livunit,calcacres,ofcard,...,card,stories,extwall,yrblt,effyr,sf,pctcomp,mod_own_adrno,longitude,latitude
count,425191.000000,4.251910e+05,4.251910e+05,425191.000000,425191.000000,425154.000000,0.0,419875.000000,424601.000000,424863.000000,...,382842.000000,382828.000000,382287.000000,382842.000000,89790.000000,3.828280e+05,2488.000000,4.097490e+05,420054.000000,420054.000000
mean,2017.027940,3.560418e+05,4.204925e+05,4.932828,2017.027940,2558.600754,NaN,1.511702,0.599641,1.030758,...,1.014181,1.460608,4.198903,1981.429399,1991.054182,2.893568e+03,35.199357,4.022809e+03,-84.407517,33.814448
std,3.695666,2.949744e+06,2.686413e+06,19.070629,3.695666,3094.502518,NaN,12.401019,4.196611,0.459061,...,0.267985,0.602640,3.024853,28.827118,17.826127,1.440965e+04,36.016064,3.331498e+05,0.104404,0.164935
min,2011.000000,0.000000e+00,0.000000e+00,1.000000,2011.000000,0.000000,NaN,0.000000,0.000000,0.000000,...,1.000000,1.000000,0.000000,1800.000000,1900.000000,0.000000e+00,0.000000,0.000000e+00,-84.844859,33.505098
25%,2013.000000,5.000000e+03,8.460000e+04,1.000000,2013.000000,436.000000,NaN,1.000000,0.050100,1.000000,...,1.000000,1.000000,1.000000,1960.000000,1980.000000,1.241000e+03,1.000000,5.100000e+02,-84.466034,33.696373
50%,2018.000000,1.399000e+05,1.969100e+05,1.000000,2018.000000,1248.000000,NaN,1.000000,0.202000,1.000000,...,1.000000,1.000000,4.000000,1989.000000,1993.000000,1.764000e+03,28.000000,1.455000e+03,-84.392070,33.778440
75%,2020.000000,3.299000e+05,3.819000e+05,1.000000,2020.000000,3481.000000,NaN,1.000000,0.403400,1.000000,...,1.000000,2.000000,7.000000,2005.000000,2005.000000,2.734000e+03,65.000000,3.945000e+03,-84.356507,33.961961
max,2022.000000,6.880000e+08,2.939893e+08,234.000000,2022.000000,77950.000000,NaN,940.000000,529.345000,30.000000,...,25.000000,43.000000,17.000000,2022.000000,2076.000000,1.970300e+06,100.000000,1.459145e+08,-84.105822,34.185969

## Determine which ParcelIDs are present and which are not
We want to check to see if the lack of a match is due only to the lack of a match in ParcelID, or specifically a lack of match (year, ParcelID) pairs.

In [16]:
unmerged_pids = pd.Series(unmerged_df["parcel_id"].unique())
print(f"{unmerged_pids.size} unmerged unique parcelIDs")

1884 unmerged unique parcelIDs

In [17]:
not_present = unmerged_pids[~unmerged_pids.isin(digest_df["parid"])]
present = unmerged_pids[unmerged_pids.isin(digest_df["parid"])]
print(f"{not_present.size} unmerged parcelIDs not present in digest")

105 unmerged parcelIDs not present in digest

In [19]:
unmerged_not_present_df = unmerged_df[unmerged_df["parcel_id"].isin(not_present)]
unmerged_present_df = unmerged_df[unmerged_df["parcel_id"].isin(present)]

In [20]:
unmerged_not_present_df.shape

(116, 74)

In [21]:
unmerged_present_df["year_before"] = unmerged_present_df["tax_year"] - 1
unmerged_present_df["year_after"] = unmerged_present_df["tax_year"] + 1

unmerged_year_status_df = pd.merge(unmerged_present_df, digest_df[["parid", "taxyr"]], left_on=["parcel_id", "year_before"], right_on=["parid", "taxyr"], how="left", suffixes=("", "_before"))
unmerged_year_status_df = pd.merge(unmerged_year_status_df, digest_df[["parid", "taxyr"]], left_on=["parcel_id", "year_after"], right_on=["parid", "taxyr"], how="left", suffixes=("", "_after"))

/var/folders/bb/g7vlcgfn14ld8_w41331g0dw0000gn/T/ipykernel_30779/2147457644.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unmerged_present_df["year_before"] = unmerged_present_df["tax_year"] - 1
/var/folders/bb/g7vlcgfn14ld8_w41331g0dw0000gn/T/ipykernel_30779/2147457644.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unmerged_present_df["year_after"] = unmerged_present_df["tax_year"] + 1

In [22]:
before = (~unmerged_year_status_df.parid_before.isna()).sum()
after = (~unmerged_year_status_df.parid_after.isna()).sum()
both = ((~unmerged_year_status_df.parid_before.isna()) & (~unmerged_year_status_df.parid_after.isna())).sum()

print(f"{before}/{unmerged_present_df.shape[0]} parcels existed before sale\n{after}/{unmerged_present_df.shape[0]} parcels existed after \n{both}/{unmerged_present_df.shape[0]} parcels existed both before and after sale.\n" + 
      f"{unmerged_present_df.shape[0] - max(before, after, both)}/{unmerged_present_df.shape[0]} parcels existed neither before nor after.")

2159/2310 parcels existed before sale
1006/2310 parcels existed after
952/2310 parcels existed both before and after sale.
151/2310 parcels existed neither before nor after.

In [23]:
unmerged_not_present_df.to_csv(os.path.join(OUT_PATH, "FULTON_UNMATCHED_NOT_PRESENT.csv"), index=False)
unmerged_year_status_df.to_csv(os.path.join(OUT_PATH, "FULTON_UNMATCHED_PRESENT.csv"), index=False)

In [24]:
neither_df = unmerged_year_status_df[((unmerged_year_status_df.parid_before.isna()) & (unmerged_year_status_df.parid_after.isna()))]

In [28]:
neither_df['parcel_id']

50      11 092003252305
51      11 092003252297
52      11 092003252289
54      08 300001320305
88      17 010800018155
             ...
1570    14 017900040226
1571    14 016300120745
1572    14 016300120794
1574    13 016000040146
1576    14 007500040072
Name: parcel_id, Length: 97, dtype: object